<a href="https://colab.research.google.com/github/arifariofficial/google-collab/blob/main/llm_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
with open("/content/drive/MyDrive/Colab Notebooks/train.txt", "r", encoding="utf-8") as f:
    text = f.read()

In [3]:
print(text)

Hello, My name is Ariful Islam. I am originally from bangladesh. I have moved to Finland in 2009. I was studying in Saimia university of applied science. It was in Lappeenranta. I lived in Lappeenranta for 7 years. After that i moved to Espoo in 2017. I was driving Lahitaxi in 2017 and 2018. I got admitted to Metropolia university of applied science to study Information Technology.



In [4]:
chars = sorted(set(text))
print(chars)
print(len(chars))

['\n', ' ', ',', '.', '0', '1', '2', '7', '8', '9', 'A', 'E', 'F', 'H', 'I', 'L', 'M', 'S', 'T', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']
41


In [5]:
string_to_int = { ch:i for i, ch in enumerate(chars)}
int_to_string = { i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])
encoded_data = encode("hello")
print(encoded_data)

[26, 23, 28, 28, 31]


In [6]:
decoded_data = decode(encoded_data)
print(decoded_data)

hello


In [7]:
import torch

In [8]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data)

tensor([13, 23, 28, 28, 31,  2,  1, 16, 40,  1, 30, 19, 29, 23,  1, 27, 34,  1,
        10, 33, 27, 24, 36, 28,  1, 14, 34, 28, 19, 29,  3,  1, 14,  1, 19, 29,
         1, 31, 33, 27, 25, 27, 30, 19, 28, 28, 40,  1, 24, 33, 31, 29,  1, 20,
        19, 30, 25, 28, 19, 22, 23, 34, 26,  3,  1, 14,  1, 26, 19, 37, 23,  1,
        29, 31, 37, 23, 22,  1, 35, 31,  1, 12, 27, 30, 28, 19, 30, 22,  1, 27,
        30,  1,  6,  4,  4,  9,  3,  1, 14,  1, 38, 19, 34,  1, 34, 35, 36, 22,
        40, 27, 30, 25,  1, 27, 30,  1, 17, 19, 27, 29, 27, 19,  1, 36, 30, 27,
        37, 23, 33, 34, 27, 35, 40,  1, 31, 24,  1, 19, 32, 32, 28, 27, 23, 22,
         1, 34, 21, 27, 23, 30, 21, 23,  3,  1, 14, 35,  1, 38, 19, 34,  1, 27,
        30,  1, 15, 19, 32, 32, 23, 23, 30, 33, 19, 30, 35, 19,  3,  1, 14,  1,
        28, 27, 37, 23, 22,  1, 27, 30,  1, 15, 19, 32, 32, 23, 23, 30, 33, 19,
        30, 35, 19,  1, 24, 31, 33,  1,  7,  1, 40, 23, 19, 33, 34,  3,  1, 10,
        24, 35, 23, 33,  1, 35, 26, 19, 

In [9]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [10]:
block_size = 8
batch_size = 4

x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print("when input is", context, "target is", target)

when input is tensor([13]) target is tensor(23)
when input is tensor([13, 23]) target is tensor(28)
when input is tensor([13, 23, 28]) target is tensor(28)
when input is tensor([13, 23, 28, 28]) target is tensor(31)
when input is tensor([13, 23, 28, 28, 31]) target is tensor(2)
when input is tensor([13, 23, 28, 28, 31,  2]) target is tensor(1)
when input is tensor([13, 23, 28, 28, 31,  2,  1]) target is tensor(16)
when input is tensor([13, 23, 28, 28, 31,  2,  1, 16]) target is tensor(40)


In [11]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [12]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-39, -54, -99,  92,  95,  56])

In [13]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [14]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [18]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [19]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [20]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[        149624944,   136146860616928, 72340172838076673],
        [                1,   136146860616928,   136146860616928]])

In [23]:
import torch
import numpy as np
import time
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [26]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00006914
CPU times: user 175 µs, sys: 0 ns, total: 175 µs
Wall time: 180 µs


In [32]:
%%time
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Torch: {elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Numpy: {elapsed_time:.8f}")

Torch: 0.00027847
Numpy: 0.15646291
CPU times: user 3.63 s, sys: 1.02 s, total: 4.65 s
Wall time: 4.67 s
