<a href="https://colab.research.google.com/github/arifariofficial/google-collab/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print("PyTorch version:", torch.__version__)
print("Is CUDA available?", torch.cuda.is_available())


PyTorch version: 2.5.1+cu121
Is CUDA available? True


### Create Your First Tensor

In [2]:
# Import PyTorch
import torch

# Create a tensor
tensor = torch.tensor([1, 2, 3, 4, 5])

# Print the tensor and its type
print("Tensor:", tensor)
print("Type:", tensor.dtype)
print("Device:", tensor.device)


Tensor: tensor([1, 2, 3, 4, 5])
Type: torch.int64
Device: cpu


###  Basic Tensor Operations

#### Creating Tensors with Specific Data Types

In [3]:
# Create a tensor with float data type
float_tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print("Float Tensor:", float_tensor)


Float Tensor: tensor([1., 2., 3., 4., 5.])


#### Performing Basic Math Operations

In [4]:
# Basic math operations
tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

print("Tensor + 10:", tensor + 10)
print("Tensor * 2:", tensor * 2)
print("Sum of Tensor:", torch.sum(tensor))


Tensor + 10: tensor([11., 12., 13., 14., 15.])
Tensor * 2: tensor([ 2.,  4.,  6.,  8., 10.])
Sum of Tensor: tensor(15.)


#### Moving a Tensor to the GPU (Optional)

In [5]:
# Move tensor to GPU
gpu_tensor = tensor.to("cuda")
print("Device of GPU Tensor:", gpu_tensor.device)


Device of GPU Tensor: cuda:0


### Tensor Reshaping and Indexing

#### Reshaping Tensors

In [12]:
# Create a tensor with 12 elements
tensor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape to a 3x4 tensor
reshaped_tensor = tensor.reshape(3, 4)
print("Reshaped Tensor (3x4):\n", reshaped_tensor)


Reshaped Tensor (3x4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


#### Accessing Specific Elements (Indexing)

In [13]:
# Access specific elements
print("First Row:", reshaped_tensor[0])       # First row
print("First Column:", reshaped_tensor[:, 0]) # First column
print("Element at [1, 2]:", reshaped_tensor[1, 2]) # Element at row 1, column 2


First Row: tensor([1, 2, 3, 4])
First Column: tensor([1, 5, 9])
Element at [1, 2]: tensor(7)


#### Slicing

In [14]:
# Extract a 2x2 block
sub_tensor = reshaped_tensor[0:2, 1:3]
print("Sub Tensor (2x2):\n", sub_tensor)


Sub Tensor (2x2):
 tensor([[2, 3],
        [6, 7]])


### Matrix Operations and Element-Wise Computations

#### Matrix Multiplication (Dot Product)
Matrix multiplication is fundamental in machine learning, especially for layers in a neural network.

In [15]:
# Create two tensors
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Perform matrix multiplication
matmul_result = torch.matmul(tensor_a, tensor_b)
print("Matrix Multiplication Result:\n", matmul_result)


Matrix Multiplication Result:
 tensor([[19, 22],
        [43, 50]])


#### Element-Wise Multiplication

In [16]:
# Element-wise multiplication
elementwise_result = tensor_a * tensor_b
print("Element-Wise Multiplication Result:\n", elementwise_result)


Element-Wise Multiplication Result:
 tensor([[ 5, 12],
        [21, 32]])


#### Tensor Aggregation

In [17]:
# Aggregation operations
print("Sum of Tensor A:", torch.sum(tensor_a))
print("Mean of Tensor A:", torch.mean(tensor_a.float()))  # Cast to float for mean
print("Max Value in Tensor A:", torch.max(tensor_a))


Sum of Tensor A: tensor(10)
Mean of Tensor A: tensor(2.5000)
Max Value in Tensor A: tensor(4)


#### Tensor Transposition
Transpose a matrix to flip its rows and columns

In [18]:
# Transpose tensor_a
transposed = tensor_a.T
print("Transposed Tensor A:\n", transposed)


Transposed Tensor A:
 tensor([[1, 3],
        [2, 4]])


### Create a Simple Neural Network

####  Import Necessary Modules

In [19]:
import torch
import torch.nn as nn
import torch.optim as optim


#### Define a Dataset

In [20]:
# Input (X) and Output (Y)
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
Y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])


#### Define the Model
A simple model with one input and one output:

In [21]:
# Define a simple feedforward neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.linear = nn.Linear(1, 1)  # 1 input, 1 output

    def forward(self, x):
        return self.linear(x)

# Initialize the model
model = SimpleNN()


#### Define the Loss and Optimizer
The loss function measures how well the model is performing, and the optimizer updates the model parameters:

In [22]:
# Mean Squared Error loss
criterion = nn.MSELoss()

# Stochastic Gradient Descent optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)


#### Train the Model
Perform multiple iterations (epochs) of training:

In [23]:
# Train the model
for epoch in range(100):  # Number of epochs
    # Forward pass: Compute predictions
    predictions = model(X)

    # Compute the loss
    loss = criterion(predictions, Y)

    # Backward pass: Compute gradients
    optimizer.zero_grad()
    loss.backward()

    # Update parameters
    optimizer.step()

    if (epoch + 1) % 10 == 0:  # Print loss every 10 epochs
        print(f"Epoch [{epoch + 1}/100], Loss: {loss.item():.4f}")


Epoch [10/100], Loss: 1.8384
Epoch [20/100], Loss: 0.2641
Epoch [30/100], Loss: 0.2108
Epoch [40/100], Loss: 0.1975
Epoch [50/100], Loss: 0.1860
Epoch [60/100], Loss: 0.1752
Epoch [70/100], Loss: 0.1650
Epoch [80/100], Loss: 0.1554
Epoch [90/100], Loss: 0.1463
Epoch [100/100], Loss: 0.1378


### Test the Model
Use the trained model to make predictions:

In [24]:
# Test the model
with torch.no_grad():  # No gradient calculation during testing
    test_input = torch.tensor([[5.0]])
    predicted_output = model(test_input)
    print(f"Prediction for input 5.0: {predicted_output.item():.2f}")


Prediction for input 5.0: 9.37
