<a href="https://colab.research.google.com/github/arifariofficial/google-collab/blob/main/PyTorch_Patrick.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.rand(3, 2)
x

tensor([[0.5264, 0.3350],
        [0.1215, 0.8963],
        [0.4440, 0.3486]])

In [ ]:
x.dtype

torch.float32

In [ ]:
x.shape

torch.Size([3, 2])

In [ ]:
print(x[:, 0])

tensor([0.5264, 0.1215, 0.4440])


In [ ]:
print(x[1, :])

tensor([0.1215, 0.8963])


In [ ]:
print(x[1,1].item()) # For one value of tensor item() can be called

0.8962602615356445
