<a href="https://colab.research.google.com/github/arifariofficial/google-collab/blob/main/voipe_ai_metropolia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy and Arrays

Array is created with the array () command, which passes items as a list (one-dimensional table) or as a list of lists (two-dimensional and multi-dimensional tables). E.g.

In [2]:
import numpy as np
x = np.array([1,3,4,5])
A = np.array([[1,3],[4,5]])

Arrays in Numpy has a shape, which indicates the number of elements in the table along each axis as a plural (tuple). E.g.

In [3]:
print(np.shape(x))
np.shape(A)

(4,)


(2, 2)

It is not appropriate to create large arrays with square brackets. Instead, arrays can be easily created to the desired size with the functions zeros (), ones (), and full (), to which information about the size of the array is conveyed as a plural. E.g.

In [4]:
Z = np.zeros(5)
print(Z)
np.shape(Z)


[0. 0. 0. 0. 0.]


(5,)

In [5]:
Z2 = np.zeros((4,5)) # notice doulbe pracets
print(Z2)
np.shape(Z2)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(4, 5)

In [7]:
Y = np.ones((2,3))
print(Y)


[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
F=np.full((7,8),11)
F

array([[11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11]])

Evenly spaced numbers can be easily generated with the linspace () and arange () functions. linspace () works by passing  an initial value, an end value, and the number of elements to it. E.g.

In [10]:
x = np.linspace(0,5,10)
print(x)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


The result is thus 10 elements between the start and end values, including the endpoints. arange () in turn takes the step length as the third parameter. E.g.

In [11]:
x2 = np.arange(0,5,0.2)
print(x2)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


Note that an array created with arange () does not reach a final value (so it works like range ()).

Random integers ) between [a, b] can be generated with the command randint (), i.e.



In [12]:
a = 1
b = 6
amount = 50
nopat = np.random.randint(a,b+1,amount)
print(nopat)

[1 1 3 5 2 3 3 2 5 1 2 3 5 1 4 4 5 1 5 5 1 2 5 2 1 3 1 4 3 4 4 2 2 5 4 5 1
 1 1 1 3 4 1 3 6 6 3 4 4 5]


Note how the endpoint is not included here, so the second parameter must be b + 1. Normally distributed random numbers are obtained with the command randn (n), where n indicates the amount of numbers to be generated.

In [13]:
x = np.random.randn(100)
print(x)

[-0.01173244  0.64494334  1.12239701 -0.54720712  0.14369018  0.46524699
 -0.32107297 -0.34988031  0.22267558 -1.25448624 -0.00511557 -0.25131858
  0.74870519 -0.52125156 -1.24273529 -0.78733816 -1.65473177  0.57301256
 -0.69970475 -0.4604746  -0.4043009   1.07465006  0.46519897 -0.0448271
  0.91692803 -0.55952068 -0.19202292  1.23763255 -0.44016741 -1.80269828
 -1.07124262  1.31118345  0.56102636  1.32955089 -0.72082989 -0.13719144
  0.87318816 -1.08309726 -0.49284764  0.48119185  1.68954025 -2.79114604
  1.15978777 -0.35109051 -1.15331607 -0.32080142 -0.1325342   0.99933953
 -1.95809387  0.41337839 -0.81956538  1.21738632  0.25020879 -0.38902476
  1.17793327 -0.04269886  0.30813761  0.93385714 -0.18156886  0.93967758
  1.30579598 -0.03499782 -0.10946951 -1.18412487 -0.10077044 -0.65959467
 -0.86553895  0.50258211  0.42620587  0.07058213 -1.00513457 -2.4151177
  0.08431232  0.65210263  0.1841964  -0.61916474 -0.13810725 -0.28238984
 -0.09685728 -0.24051261 -0.41849554  1.2935687  -1.5

The random () command produces random numbers evenly distributed over a semi-open interval [0.0, 1.0). So these are decimal numbers. E.g.

In [14]:
x = np.random.random(10)
print(x)

[0.64552587 0.69872115 0.25180523 0.09446671 0.53308371 0.80610004
 0.71811407 0.95865892 0.70098358 0.34979121]


The numbers of dimensions and elements in the table are determined by the attributes ndim and size. E.g.

In [18]:
x = np.array([1,3,4,5])
A = np.array([[1,3],[4,5]])

print("x size: ", x.size)
print("x dim: ", x.ndim)
print("A size: ", A.size)
print("A size: ", A.ndim)

x size:  4
x dim:  1
A size:  4
A size:  2


# Cutting Matrices (indexing)

Cutting a one-dimensional array is done in the usual way with square brackets by indexing. Remember that places are indexed from zero!

The two-dimensional array is indexed (cut) by two indexes within one square bracket:

In [20]:
A = np.array([[1,2,3],[4,5,6]])
print(A[0,0])
print(A[0,1])

1
2


The three-dimensional array is cut with three indexes, respectively.

A negative index works in the same way as with lists, i.e. it counts from the end. A colon is used to cut an entire row or column. E.g.

In [21]:
A[:,0] # fisrt column, ":"reads all rows

array([1, 4])

In [22]:
A[0,:] # first row, ":" reads all columns

array([1, 2, 3])

The colon can also be used to create index spaces with the start: end: step syntax, so that the intersection no longer targets the end. The index spacing can be used to index both rows and columns. E.g.

In [23]:
A = np.array([1,2,3,4,5,6,7,8,9])
A[0:6:1]


array([1, 2, 3, 4, 5, 6])

In [24]:
# start = 0, end = 9, step = 3
A[0:9:3]


array([1, 4, 7])

Items can be updated with a combination of an signing statement and a cut. E.g.

In [25]:
A = np.array([[1,2,3],[4,5,6]])
A[0,0] = 17
A[1,:] = [11,12,13]
A

array([[17,  2,  3],
       [11, 12, 13]])

Tables can be stacked with the vstack () command. E.g.

In [26]:
A = np.array([[1,2,3],[4,5,6]])

In [27]:
new = np.vstack((A,A))
new

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

This method can therefore be used to add horizontal rows to the beginning or end of a table. However, stackable tables must be compatible in shape. Horizontal stacking connects tables side by side. E.g.

In [28]:
new2 = np.hstack((A,A))
new2

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Deleting a row and column is done with the delete command, to which information about the index of the row / column to be deleted and the dimension of the deletion operation must be passed (0 = for rows, 1 = for columns).

In [29]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.delete(A,[0],0)
B

array([[4, 5, 6]])

In [30]:
C = np.delete(A,[1],0)
C

array([[1, 2, 3]])

In [31]:
D = np.delete(A,[0],1)
D

array([[2, 3],
       [5, 6]])

A single item cannot be removed as it would make holes in the matrix.

The table can be traversed (iterated) in many different ways. For example, one line at a time

In [32]:
A = np.array([1,2,3,4,5,6])
A = A.reshape(2,3)
A


array([[1, 2, 3],
       [4, 5, 6]])

Row by row

In [33]:
n,m = np.shape(A)
for i in range(n):
    print("Row",i,"is",A[i,:])


Row 0 is [1 2 3]
Row 1 is [4 5 6]


Column by column

In [34]:
for j in range(m):
    print("Column",j,"is",A[:,j])

Column 0 is [1 4]
Column 1 is [2 5]
Column 2 is [3 6]


One element at a time

In [35]:
for i in range(n):
    for j in range(m):
        print("Element",i,j,"is",A[i,j])

Element 0 0 is 1
Element 0 1 is 2
Element 0 2 is 3
Element 1 0 is 4
Element 1 1 is 5
Element 1 2 is 6


Another way to iterate the table item by item is to use a single iteration structure. This is especially useful for high-dimension arrays

In [36]:
for a in np.nditer(A):
    print(a)

1
2
3
4
5
6


Notice how here again the order goes to the lines above (dimension / axis 0).

# Calculations with Matrics

As with regular numbers, calculations can also be performed on matrices. Addition and subtraction work on the tables item by item, ie the counterparts in the same place in the two matrices are added together (or subtracted from each other). Note that the list structure in Python does not support these kinds of vectorized calculations, Numpy library is needed. E.g.

In [38]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,9],[4,-1]])


In [39]:
A+B

array([[ 4, 11],
       [ 7,  3]])

In [40]:
A-B

array([[-2, -7],
       [-1,  5]])

Multiplication and division also work with the same idea.

In [41]:
A*B

array([[ 3, 18],
       [12, -4]])

In [42]:
A/B

array([[ 0.33333333,  0.22222222],
       [ 0.75      , -4.        ]])

This way, you can create a large matrix that contains the desired number for each item (or use the full () command). E.g.

In [45]:
T = 5*np.ones((10,10))
print(T)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


These calculations, of course, require that the matrices A and B are the same size (shape the same) or that the other is a mere number. E.g.

In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,9],[4,-1]])


In [48]:
A-1

array([[0, 1],
       [2, 3]])

In [49]:
B+2

array([[ 5, 11],
       [ 6,  1]])

succeed without the use of ones (). The increase in power by item is done with the command



In [50]:
A**2

array([[ 1,  4],
       [ 9, 16]])

There is also a completely unique multiplication (matrix product, matrix multiplication) for matrices, which does not work element by element but corresponds to the concept of multiplication in linear algebra. The matrix product AB is defined if the number of columns in A is the same as the number of rows in B (the exact definition can be found in Wikipedia, for example).

Numpy's matmul () command or operator @ performs this multiplication. E.g.

In [52]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,9],[4,-1]])

np.matmul(A,B) # or A @ B

array([[11,  7],
       [25, 23]])

For one-dimensional tables (i.e. vectors), dot () produces the point product (scalar product) of the vectors. In that case, the compatibility of the forms of income factors is not taken into account.

In [54]:
x = np.array([1,3,4,5])
x.dot(x)

51

It is also possible to calculate the matrix product between the matrix and the vertical vector, in which case an elementary product would not even be possible. E.g.

In [56]:
A = np.array([[1,2],[3,4]])
b = np.array([[5],[7]])
np.matmul(A,b)

array([[19],
       [43]])

So note that matmul () / dot () does not compute an elementary product but something completely different (related to a linear algebra).

In addition to the basic calculations, the application of elementary functions to the matrix is ​​done item by item. E.g.

In [57]:
np.sqrt(A) # the square root of each item
np.sin(A)
np.cos(A)
np.tan(A)
np.log(A)
np.exp(A)
np.log10(A)
np.log2(A)

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

It is important to use the numpy library and not the math library, which also has elementary functions, but they do not work with matrices.

Comparison operators also target matrices by item. E.g.

In [59]:
A = np.array([[1,2],[3,4]])

In [61]:
A > 1


array([[False,  True],
       [ True,  True]])

In [62]:
A <= 0

array([[False, False],
       [False, False]])

The result is a matrix formed from the truth values ​​True and False, to which the functions any () / all () can be assigned, which tells whether one of the truth values ​​is True and, respectively, whether all the values ​​are True. E.g.

In [63]:
np.all(A>1)

False

In [64]:
np.any(A>1)

True

Operators can be used at the same time as the cut to select only items from a table that fulfill any of the conditions. E.g.



In [65]:
A = np.array([1,2,3,4,5,6,7])
B = A[A>3]

This is based on the fact that the cut can be made using the list as indexes.

Let's go back briefly to the matrix product. Consider a pair of equations formed by two equations

\begin{cases}
2x+y=11\\
-4x+3y=3
\end{cases}

This can be represented by (vertical) vectors in the form

\begin{pmatrix}
2x+y\\
-4x+3y
\end{pmatrix}=\begin{pmatrix}
11\\
3
\end{pmatrix}

when the equality (comparison) of the vectors is handled item by item. However, it now appears that the left side of the previous formula can be written as a multiplication of the matrix and the vector, in which case the equation is

\begin{pmatrix}
2&1\\
-4&3
\end{pmatrix}\begin{pmatrix}
x\\
y
\end{pmatrix}=\begin{pmatrix}
11\\
3
\end{pmatrix}

In short, this is where A X = b, where A is the 2x2 matrix, X is (vertical) vector composed by x and y  and b is (vertical) vector on the right. Solving a set of equations can be understood by looking for the inverse of the matrix A \implies A^{-1} and multiplying the vector by  b. Thus the solution is a vertical vector X = A^{- 1} b, from which we can extract x and y. Here, all multiplications are specifically matrix products. The same idea works for a larger group of equations, i.e., several unknown variables.

In practice, the solution of the group of equations is not done through the inverse matrix because it is quite a heavy operation for large matrices. Instead, other methods are used, we won’t go into details here. However, it is noted that numpy can solve a group of equations with the command solve (). For example, in the case of the previous situation

In [67]:
A = np.array([[2,1],[-4,3]])
b = np.array([11,3])
X = np.linalg.solve(A,b)
print(X)

[3. 5.]


If necessary, the inverse matrix is ​​determined by the command inv () and can be used to check that the solution is correct.

In [68]:
Ainv = np.linalg.inv(A)
print(np.matmul(Ainv,b))

[3. 5.]


# Statistical Functions

Many statistical indicators can be calculated from the numerical values in the table. The sum is calculated with the command sum (), which can optionally be given as the second argument the number of the axis over which the sum is calculated. E.g.

In [70]:
A = np.array([[1,2,3],[4,5,6]])
np.sum(A)


21

In [71]:
np.sum(A,0) # column sums, summed along rows


array([5, 7, 9])

In [72]:
np.sum(A,1) # row sums, summed along the columns

array([ 6, 15])

The product is calculated similarly with the prod () command.

In [74]:
np.prod(A)


720

In [75]:
np.prod(A,0)


array([ 4, 10, 18])

In [76]:
np.prod(A,1)

array([  6, 120])

There are also cumulative variants cumsum () and cumprod () for sum and result.

The largest and smallest elements are found with the min () / max () commands. E.g.

In [77]:
np.min(A)
np.min(A,0)
np.min(A,1)
np.max(A)
np.max(A,0)
np.max(A,1)

array([3, 6])

The average of the elements is calculated with the function mean (), which can also be assigned to a specific axis.

In [80]:
A = np.array([[1,2,3],[4,5,6]])

In [81]:
np.mean(A)


3.5

In [82]:
np.mean(A,0)


array([2.5, 3.5, 4.5])

In [83]:
np.mean(A,1)

array([2., 5.])

The median, ie the "middle" value of the numerical values, is determined by the function median ()

In [84]:
np.median(A)


3.5

In [85]:
np.median(A,0)


array([2.5, 3.5, 4.5])

In [86]:
np.median(A,1)

array([2., 5.])

The variance and its standard root deviation measure how far the numbers are from their mean. For these, there are functions var () and std ()

In [87]:
np.std(A)
np.std(A,0)
np.std(A,1)
np.var(A)
np.var(A,0)
np.var(A,1)

array([0.66666667, 0.66666667])

# About Data Types

The numpy library supports the following key data types: int8, int16, int32, int64, float16, float32, float64, uint8, uint16, uint32, uint64,  where numbers indicate the number of bits used and uint means an unsigned integer.

These can be specified when creating a table so that the items in the table are of the desired data type. E.g.

In [89]:
A = np.array([1,2,3,4,5,6],dtype="int8")

The data type of the table can be checked with the dtype attribute. E.g.

In [90]:
A.dtype

dtype('int8')

Tables can be converted from one data type to another with the astype () command, which is given a new data type parameter as a string. E.g.



In [91]:
A.astype("int16")

array([1, 2, 3, 4, 5, 6], dtype=int16)

The type of data is important for memory usage (at least in critical applications), as presenting numbers with a smaller number of bits can save memory. On the flip side, large numbers cannot be represented by a small number of bits. The amount of memory required by a table element in bytes (!) Is determined by the itemsize attribute, in which case the memory required by the entire table is the same as A.itemsize * A.size or A.nbytes. E.g

In [92]:
A.itemsize


1

In [93]:
A.nbytes


6

In [94]:
A2 = np.array([1,2,3,4,5,6],dtype="int64")


In [95]:
A2.nbytes

48

Notice how presenting the same information with a different data type can take up to eight times more memory space! This already matters if the table is hundreds of megabytes in size, not to mention gigabytes.

With an unsigned integer type (uint), you should be careful, because when it encounters a negative number, an underflow occurs and the results can be catastrophic.

In [96]:
A = np.array([1,2,3,4,5,6],dtype="uint8")
A-7

array([250, 251, 252, 253, 254, 255], dtype=uint8)

However, the advantage of the uint type is that the same number of bits can represent twice as many positive numbers as the int type, because the int type prepares to handle roughly the same number of negative and positive numbers. The range of figures that can be displayed for different data types is shown in the following table.


| Data Type  | Minimum Value             | Maximum Value               |
|------------|---------------------------|-----------------------------|
| **int8**   | -128                      | 127                         |
| **int16**  | -32,768                   | 32,767                      |
| **int32**  | -2,147,483,648            | 2,147,483,647               |
| **int64**  | -9,223,372,036,854,775,808| 9,223,372,036,854,775,807   |
| **uint8**  | 0                         | 255                         |
| **uint16** | 0                         | 65,535                      |
| **uint32** | 0                         | 4,294,967,295               |
| **uint64** | 0                         | 18,446,744,073,709,551,615  |



In normal programming, there is usually no need to care about the type of data, but at some point it is good to be at least aware of this at some point.

Complete documentation on data types can be found at

https://numpy.org/doc/stable/reference/arrays.dtypes.html

There is another thing about floating point types that every programmer should be aware of. Namely, between 0..1 there are infinitely many decimal numbers. Because the computer uses only a finite number of bits to display floating-point numbers, some floating-point numbers must be displayed inaccurately. For example, the number 1/3 cannot be represented as a ending decimal representation. Thus, an approximation is used to present it, which can be accurately represented. This approximation is

In [98]:
print(str.format('{0:.25f}', 1/3))


0.3333333333333333148296163


Another example of the same phenomenon is summation

In [99]:
0.1+0.1+0.1+0.1+0.1+0.1+0.1+0.1

0.7999999999999999

Now the reason is that the number 0.1 cannot be represented as a finite bit string exactly, but we have to use approximations inside the computer:

In [100]:
print(str.format('{0:.25f}', 0.1))

0.1000000000000000055511151


That is: when calculating with floating-point numbers, you have to deal with such rounding errors.

It is convenient to present large and small floating-point numbers with scientific notation. The presentation is e.g.

1.0e+10

meaning the number 1.0 * 10 ** 10 or 10 ** 10 or 10000000. Similarly, e.g. 1.23e-5 means the number 1.23 * 10 ** (- 5) or 0.0000123. If such an exponential representation were not used, then we would have to read a long series of numbers such as

123000000000000000000000000000

which is not very friendly to the human eye.

