<a href="https://colab.research.google.com/github/arifariofficial/google-collab/blob/main/voipe_ai_metropolia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy and Arrays

Array is created with the array () command, which passes items as a list (one-dimensional table) or as a list of lists (two-dimensional and multi-dimensional tables). E.g.

In [1]:
import numpy as np
x = np.array([1,3,4,5])
A = np.array([[1,3],[4,5]])

Arrays in Numpy has a shape, which indicates the number of elements in the table along each axis as a plural (tuple). E.g.

In [2]:
np.shape(x)
np.shape(A)

(2, 2)

It is not appropriate to create large arrays with square brackets. Instead, arrays can be easily created to the desired size with the functions zeros (), ones (), and full (), to which information about the size of the array is conveyed as a plural. E.g.

In [3]:
Z = np.zeros(5)
print(Z)
np.shape(Z)
Z2 = np.zeros((4,5)) # notice doulbe pracets
print(Z2)
np.shape(Z2)
Y = np.ones((2,3))
print(Y)
F=np.full((7,8),11)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


Evenly spaced numbers can be easily generated with the linspace () and arange () functions. linspace () works by passing  an initial value, an end value, and the number of elements to it. E.g.

In [4]:
x = np.linspace(0,5,10)
print(x)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


The result is thus 10 elements between the start and end values, including the endpoints. arange () in turn takes the step length as the third parameter. E.g.

In [5]:
x2 = np.arange(0,5,0.2)
print(x2)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


Note that an array created with arange () does not reach a final value (so it works like range ()).

Random integers ) between [a, b] can be generated with the command randint (), i.e.



In [8]:
a = 1
b = 6
amount = 50
nopat = np.random.randint(a,b+1,amount)
print(nopat)

[2 1 5 2 6 4 3 1 5 5 1 6 4 3 6 3 5 3 5 5 4 6 4 5 1 2 5 5 4 3 1 3 1 3 3 3 3
 6 2 6 6 6 4 3 6 5 3 6 6 3]


Note how the endpoint is not included here, so the second parameter must be b + 1. Normally distributed random numbers are obtained with the command randn (n), where n indicates the amount of numbers to be generated.

In [10]:
x = np.random.randn(100)
print(x)

[-0.12207751 -1.03054963 -0.43719322  0.66125251  0.25367787 -0.24504387
 -0.196559    0.5697133   0.88038722  0.37992511 -0.40925758 -0.33593796
  1.04597755 -0.21608818  0.24546013  0.78679044  1.45415473 -1.10341216
 -0.65105654  0.57618414 -0.10245494 -0.31945751 -0.17198758  2.70137003
  0.07683828 -0.04186702 -2.02236839  1.07534315  0.13329479 -0.22704565
 -1.27773435 -0.64772401  1.64031952  1.77176433 -1.24913805  1.73868387
 -1.76481573  0.57080288 -1.22861503  0.6743565  -0.51390583 -0.2533642
  0.43745178 -1.49230157 -0.56711418  0.95965269  0.38359673 -1.75311741
 -1.64109225 -0.12333003 -0.0818882   0.32977729  0.05819244 -0.58633599
  0.13975436  0.7635825   0.60616957  0.91144477  0.44008056  1.17071319
 -1.10534187 -2.20117458 -0.84398515  0.19047511 -0.34702168 -1.12040301
  1.60602626 -1.26097495  0.10577037  0.58458622  0.26044304  0.81964497
  0.54114533  1.38498521 -0.37084271  2.45436748 -1.2269657   0.17376901
  0.02425554  0.53911048 -1.26629042 -0.46660322 -0.

The random () command produces random numbers evenly distributed over a semi-open interval [0.0, 1.0). So these are decimal numbers. E.g.

In [12]:
x = np.random.random(10)
print(x)

[0.34684596 0.41573384 0.87357224 0.01526896 0.07973752 0.80508313
 0.3435736  0.39690341 0.24704133 0.53040814]


The numbers of dimensions and elements in the table are determined by the attributes ndim and size. E.g.

In [13]:
x.size
x.ndim
A.size
A.ndim

2

# Cutting Matrices (indexing)

Cutting a one-dimensional array is done in the usual way with square brackets by indexing. Remember that places are indexed from zero!

The two-dimensional array is indexed (cut) by two indexes within one square bracket:

In [15]:
A = np.array([[1,2,3],[4,5,6]])
print(A[0,0])
print(A[0,1])

1
2


The three-dimensional array is cut with three indexes, respectively.

A negative index works in the same way as with lists, i.e. it counts from the end. A colon is used to cut an entire row or column. E.g.

In [16]:
A[:,0] # fisrt column, ":"reads all rows

array([1, 4])

In [17]:
A[0,:] # first row, ":" reads all columns

array([1, 2, 3])

The colon can also be used to create index spaces with the start: end: step syntax, so that the intersection no longer targets the end. The index spacing can be used to index both rows and columns. E.g.

In [33]:
A = np.array([1,2,3,4,5,6,7,8,9])
A[0:6:1]


array([1, 2, 3, 4, 5, 6])

In [35]:
# start = 0, end = 9, step = 3
A[0:9:3]


array([1, 4, 7])

Items can be updated with a combination of an signing statement and a cut. E.g.

In [37]:
A = np.array([[1,2,3],[4,5,6]])
A[0,0] = 17
A[1,:] = [11,12,13]
A

array([[17,  2,  3],
       [11, 12, 13]])

Tables can be stacked with the vstack () command. E.g.

In [41]:
A = np.array([[1,2,3],[4,5,6]])

In [42]:
new = np.vstack((A,A))
new

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

This method can therefore be used to add horizontal rows to the beginning or end of a table. However, stackable tables must be compatible in shape. Horizontal stacking connects tables side by side. E.g.

In [43]:
new2 = np.hstack((A,A))
new2

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Deleting a row and column is done with the delete command, to which information about the index of the row / column to be deleted and the dimension of the deletion operation must be passed (0 = for rows, 1 = for columns).

In [62]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.delete(A,[0],0)
B

array([[4, 5, 6]])

In [63]:
C = np.delete(A,[1],0)
C

array([[1, 2, 3]])

In [71]:
D = np.delete(A,[0],1)
D

array([[2, 3],
       [5, 6]])

A single item cannot be removed as it would make holes in the matrix.

The table can be traversed (iterated) in many different ways. For example, one line at a time

In [83]:
A = np.array([1,2,3,4,5,6])
A = A.reshape(2,3)
A


array([[1, 2, 3],
       [4, 5, 6]])

Row by row

In [84]:
n,m = np.shape(A)
for i in range(n):
    print("Row",i,"is",A[i,:])


Row 0 is [1 2 3]
Row 1 is [4 5 6]


Column by column

In [85]:
for j in range(m):
    print("Column",j,"is",A[:,j])

Column 0 is [1 4]
Column 1 is [2 5]
Column 2 is [3 6]


One element at a time

In [86]:
for i in range(n):
    for j in range(m):
        print("Element",i,j,"is",A[i,j])

Element 0 0 is 1
Element 0 1 is 2
Element 0 2 is 3
Element 1 0 is 4
Element 1 1 is 5
Element 1 2 is 6


Another way to iterate the table item by item is to use a single iteration structure. This is especially useful for high-dimension arrays

In [87]:
for a in np.nditer(A):
    print(a)

1
2
3
4
5
6


Notice how here again the order goes to the lines above (dimension / axis 0).